// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function getClassName(intent) {
  switch (intent) {
    case 0 : 
        return "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline";
    case 1 : 
        return "bg-gray-300 hover:bg-gray-500 text-gray font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline";
    case 2 : 
        return "inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800";
    
  }
}

function Button(Props) {
  var title = Props.title;
  var match = Props.onClick;
  var onClick = match !== undefined ? match : (function (_e) {
        return /* () */0;
      });
  var match$1 = Props.intent;
  var intent = match$1 !== undefined ? match$1 : /* Primary */0;
  var match$2 = Props.type_;
  var type_ = match$2 !== undefined ? match$2 : "button";
  return React.createElement("button", {
              className: getClassName(intent),
              type: type_,
              onClick: onClick
            }, title);
}

var make = Button;

exports.getClassName = getClassName;
exports.make = make;
/* react Not a pure module */
