// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Form(Props) {
  var children = Props.children;
  var onSubmit = Props.onSubmit;
  return React.createElement("form", {
              className: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4",
              onSubmit: onSubmit
            }, children);
}

function Form$Input(Props) {
  var id = Props.id;
  var type_ = Props.type_;
  var onChange = Props.onChange;
  var value = Props.value;
  var match = Props.placeholder;
  var placeholder = match !== undefined ? match : "";
  return React.createElement("input", {
              className: "appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
              id: id,
              placeholder: placeholder,
              type: type_,
              value: value,
              onChange: onChange
            });
}

var Input = /* module */[/* make */Form$Input];

var make = Form;

exports.make = make;
exports.Input = Input;
/* react Not a pure module */
