// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function valueFromEvent(evt) {
  return evt.target.value;
}

function QuestionComposer(Props) {
  var question = Props.question;
  var onAddOption = Props.onAddOption;
  var onChangeQuestionTitle = Props.onChangeQuestionTitle;
  var onChangeQuestionOption = Props.onChangeQuestionOption;
  var renderOptions = $$Array.of_list(List.mapi((function (i, option) {
              return React.createElement("div", undefined, React.createElement("label", {
                              htmlFor: "options"
                            }, React.createElement("span", undefined, "Option " + String(i + 1 | 0)), React.createElement("br", undefined), React.createElement("input", {
                                  placeholder: "an answer...",
                                  type: "text",
                                  value: option[/* title */0],
                                  onChange: (function (e) {
                                      return Curry._3(onChangeQuestionOption, question[/* title */0], option[/* title */0], e.target.value);
                                    })
                                })));
            }), question[/* options */1]));
  return React.createElement("section", undefined, React.createElement("div", undefined, React.createElement("label", {
                      htmlFor: "question"
                    }, React.createElement("span", undefined, "What do you want to ask?"), React.createElement("br", undefined), React.createElement("input", {
                          placeholder: "the question...",
                          type: "text",
                          value: question[/* title */0],
                          onChange: (function (e) {
                              return Curry._2(onChangeQuestionTitle, question[/* title */0], e.target.value);
                            })
                        }))), React.createElement("div", undefined, React.createElement("span", undefined, "What are possible answers?"), renderOptions), React.createElement("button", {
                  onClick: (function (_e) {
                      return Curry._1(onAddOption, question[/* title */0]);
                    })
                }, "Add Option"));
}

var make = QuestionComposer;

exports.valueFromEvent = valueFromEvent;
exports.make = make;
/* react Not a pure module */
