// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function makeEmpty($staropt$star, $staropt$star$1, id) {
  var title = $staropt$star !== undefined ? $staropt$star : "";
  var options = $staropt$star$1 !== undefined ? $staropt$star$1 : /* [] */0;
  return /* record */[
          /* id */id,
          /* title */title,
          /* options */options
        ];
}

function appendQuestion(questions) {
  var newQuestion = makeEmpty(undefined, undefined, String(List.length(questions)));
  return Pervasives.$at(questions, /* :: */[
              newQuestion,
              /* [] */0
            ]);
}

exports.makeEmpty = makeEmpty;
exports.appendQuestion = appendQuestion;
/* No side effect */
