// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

function Text$Heading(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-black-700 text-xl font-semibold"
            }, children);
}

var Heading = /* module */[/* make */Text$Heading];

function Text$Span(Props) {
  var match = Props.uppercase;
  var uppercase = match !== undefined ? match : false;
  var children = Props.children;
  var className = "text-gray-500 " + (
    uppercase ? "uppercase text-xs font-bold" : "text-base"
  );
  return React.createElement("span", {
              className: className
            }, children);
}

var Span = /* module */[/* make */Text$Span];

function $$Text(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "text-black-700 text-base"
            }, children);
}

var make = $$Text;

exports.str = str;
exports.Heading = Heading;
exports.Span = Span;
exports.make = make;
/* react Not a pure module */
