// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function makeEmpty($staropt$star, $staropt$star$1, id) {
  var title = $staropt$star !== undefined ? $staropt$star : "";
  var isCorrect = $staropt$star$1 !== undefined ? $staropt$star$1 : false;
  return /* record */[
          /* id */id,
          /* title */title,
          /* isCorrect */isCorrect
        ];
}

function appendEmpty(options) {
  var newOption = makeEmpty(undefined, undefined, String(List.length(options) + 1 | 0));
  return Pervasives.$at(options, /* :: */[
              newOption,
              /* [] */0
            ]);
}

var QuestionOption = /* module */[
  /* makeEmpty */makeEmpty,
  /* appendEmpty */appendEmpty
];

function makeEmpty$1($staropt$star, $staropt$star$1, id) {
  var title = $staropt$star !== undefined ? $staropt$star : "";
  var options = $staropt$star$1 !== undefined ? $staropt$star$1 : /* [] */0;
  return /* record */[
          /* id */id,
          /* title */title,
          /* options */options
        ];
}

function appendEmpty$1(questions) {
  var newQuestion = makeEmpty$1(undefined, undefined, String(List.length(questions) + 1 | 0));
  return Pervasives.$at(questions, /* :: */[
              newQuestion,
              /* [] */0
            ]);
}

var Question = /* module */[
  /* makeEmpty */makeEmpty$1,
  /* appendEmpty */appendEmpty$1
];

exports.QuestionOption = QuestionOption;
exports.Question = Question;
/* No side effect */
